window.PORTFOLIO_ARCHIVE_DATA = {
  sectionTranslations: {
    operating: "我如何把信号转化为可验证的内容结果。",
    signals: "先看可验证的数据，再解释内容为什么有效。",
    index: "四套项目系统，共用一套内容增长方法。",
    contact: "一起构建面向未来的内容系统。",
  },
  methods: [
    ["01", "OBSERVE", "观察", "观察用户真实需求和具体使用场景，不只看点赞和表面反馈。"],
    ["02", "DECODE", "拆解", "拆解内容背后的情绪、身份、申请焦虑和购买动机。"],
    ["03", "TRANSLATE", "转译", "把科研、AI、国际组织等复杂内容，转译成用户愿意停下来理解的内容入口。"],
    ["04", "PROVE", "验证", "用点击、私信、留资和销售反馈，判断内容到底有没有产生真实价值。"],
    ["05", "ITERATE", "迭代", "根据真实反馈继续调整选题、视觉、人设和转化路径。"],
  ],
  signals: [
    ["¥79.6K", "Paid Media Spend", "累计付费投放金额"],
    ["661.9K", "Impressions", "内容曝光量"],
    ["325", "Private-message Inquiries", "私信咨询进线"],
    ["¥391", "Optimized Lead Cost", "优化后单条留资成本"],
  ],
  projects: [
    {
      id: "project-01",
      number: "01",
      title: "PAID RESEARCH PRODUCT CONTENT SYSTEM",
      subtitle: "Research content, measured by intent.",
      subtitleCn: "用真实咨询与留资，检验科研内容是否有效。",
      cnTitle: "科研产品内容增长系统",
      keywords: ["Research content", "Paid acquisition", "Lead conversion"],
      cnKeywords: ["科研内容", "付费获客", "留资转化"],
      meta: {
        role: "内容策略 / 小红书账号运营 / 投放素材测试 / 数据复盘 / 销售反馈协同",
        period: "2026.01–2026.07",
        scope: "科研蓝V / 付费投放 / 前沿科研选题 / 私信进线 / 留资转化",
        tools: "小红书聚光 / 可画 / Excel / AI内容工具",
      },
      problem: [
        "脑科学、脑机接口、神经科学这些前沿内容，点击和咨询表现一直不错，但销售反馈却是“不好成交”，更希望账号吸引来一些更小白的用户。",
        "这件事让我觉得有点矛盾：如果内容可以持续带来更低成本的点击和咨询，问题可能不只是“流量不准”。",
      ],
      hypothesis: [
        "我的判断是，前沿科研内容吸引来的并不是低质量用户，而是更懂专业、更会追问细节的高认知用户。",
        "内容把人找对了，但现有产品和销售话术更习惯承接标准化、低认知需求，所以咨询越专业，后端反而越难接住。",
      ],
      actionIntro: "我围绕脑科学、脑机接口、AI芯片、半导体、公共卫生、生物医学等方向持续测试内容选题。",
      actions: [
        "调整选题结构，把产业热点转译成申请者能理解的科研方向",
        "测试不同封面、标题和投放素材",
        "观察点击、私信进线、留资成本和销售反馈",
        "区分国内与海外用户、不同城市层级和投放时段",
        "对长期投放数据与近期优化阶段进行对比",
        "将销售端反馈重新带回内容侧复盘，而不是只看点赞和阅读量",
      ],
      insight: [
        "不是所有低转化都等于流量不准。",
        "前沿内容能够带来更低的点击成本和真实咨询，说明用户需求存在。真正的转化断点，是高认知用户已经被内容吸引过来，但产品分层、专业承接和销售话术没有同步跟上。",
        "有时候不是内容没有找到用户，而是内容把用户带到了比产品更前面的位置。",
      ],
      anonymousCase: "一名医学专业学生提出国内高水平学术成果需求并完成付费，但机构现有产品无法承接对应成果路径，最终存在退费风险。这个案例进一步验证：精准线索不一定等于可成交线索，产品能力决定了流量价值能否真正留下。",
      slots: [
        { id: "P1-01", title: "Paid Dashboard", content: "长期投放与近期优化窗口数据", ratio: "2 × 16:9", note: "规模、点击与留资成本变化", privacy: "Public Evidence", multiple: true, placeholders: ["assets/cetus/research/paid-dashboard.png", "assets/cetus/research/paid-optimization-dashboard.png"] },
        { id: "P1-02", title: "Research Account Profile", content: "科研蓝V账号、受众画像与内容诊断", ratio: "4 × 4:3", note: "账号定位、目标人群与内容系统", privacy: "Public Account Check", multiple: true, placeholders: ["assets/cetus/research/account-profile.png", "assets/cetus/research/research-public-account.png", "assets/cetus/research/research-audience-profile.png", "assets/cetus/research/research-account-diagnostics.png"] },
        { id: "P1-03", title: "Selected Research Posts", content: "跑得较好的科研内容样本", ratio: "8 × 3:4", note: "脑科学 / AI / 公共卫生 / 生化 / 金融科研", privacy: "Content Review", multiple: true, placeholders: ["assets/cetus/research/post-psychology.png", "assets/cetus/research/post-bci.png", "assets/cetus/research/post-public-health.png", "assets/cetus/research/post-ai-research.png", "assets/cetus/research/post-psychology-collection.png", "assets/cetus/research/post-nyu-ai-project.png", "assets/cetus/research/post-biochemistry.png", "assets/cetus/research/post-finance-research.png"] },
        { id: "P1-04", title: "Lead & Consultation Evidence", cnTitle: "咨询与后端承接", content: "从私信咨询、方向匹配到后端承接的真实沟通记录", ratio: "4 × 4:3", note: "真实需求、专业追问与承接动作", privacy: "User-approved evidence", multiple: true, placeholders: ["assets/cetus/research/lead-consultation-education.jpg", "assets/cetus/research/lead-consultation-bme.jpg", "assets/cetus/research/lead-consultation-bioscience.jpg", "assets/cetus/research/lead-consultation-followup.jpg"] },
      ],
    },
    {
      id: "project-02",
      number: "02",
      title: "INTERNATIONAL ORGANIZATION CONTENT SYSTEM",
      subtitle: "Authority meets persona.",
      subtitleCn: "官方权威负责确认，人设内容负责拉近距离。",
      cnTitle: "国际组织内容系统",
      keywords: ["Official authority", "Persona trust", "Paid testing"],
      cnKeywords: ["官方权威", "人设信任", "付费测试"],
      meta: {
        role: "账号定位 / 内容策略 / 蓝V投流内容 / KOS人设表达",
        period: "2025–2026",
        scope: "联合国蓝V / KOS联合国 / 国际组织产品内容 / 用户兴趣教育",
        tools: "小红书 / 可画 / AI内容工具",
      },
      problem: [
        "国际组织产品很容易出现两个问题。官方账号太像招生广告，用户能看到项目信息，但很难产生代入感。",
        "KOS账号如果只讲个人体验，又容易缺少权威感和产品可信度。如果两个账号只是重复发同一种内容，也不会真正增加信任。",
      ],
      hypothesis: [
        "同一个产品线需要两种不同的内容层级。蓝V回答的是：这个项目是否可信、具体包含什么。",
        "KOS回答的是：这件事和我有什么关系、为什么值得我了解。两种账号分别承担权威确认和心理距离缩短。",
      ],
      actionIntro: "我把国际组织内容拆成官方账号层和人设账号层，两种账号围绕同一用户需求展开，但不直接复制同一种表达。",
      actions: [
        "蓝V：项目权威信息 / 产品说明 / 付费投放测试 / 申请背景价值解释 / 咨询入口",
        "KOS联合国：真人化叙事 / 国际组织履历想象 / 实习路径解释 / 申请场景教育 / 降低硬广感",
      ],
      insight: [
        "权威和人设不是两种账号风格，而是信任链路里的两个阶段。",
        "用户需要先确认项目是真的、内容是可靠的，再判断它是否和自己的申请、履历和未来路径有关。蓝V负责建立可信度，KOS负责降低距离感。",
      ],
      slots: [
        { id: "P2-01", title: "Official Account Layer", content: "蓝V联合国账号主页或内容矩阵", ratio: "16:10", note: "官方权威层", privacy: "Account ID Check", placeholder: "assets/cetus/un/official-account-grid.png" },
        { id: "P2-02", title: "Persona Account Layer", content: "KOS联合国账号主页", ratio: "16:10", note: "人设信任层", privacy: "Account ID Check", placeholder: "assets/cetus/un/persona-profile.png" },
        { id: "P2-03", title: "Official Content Samples", content: "蓝V联合国代表内容", ratio: "2–3 × 3:4", note: "Qualitative Signal / Content Role", privacy: "Content Review", multiple: true, placeholder: "assets/cetus/un/official-content-summer.png" },
        { id: "P2-04", title: "Persona Content Samples", content: "KOS联合国代表内容", ratio: "2–3 × 3:4", note: "Audience Stage / Soft Trust", privacy: "Content Review", multiple: true, placeholder: "assets/cetus/un/persona-account-grid.png" },
      ],
    },
    {
      id: "project-03",
      number: "03",
      title: "KOS PERSONA LAB",
      subtitle: "Persona as a content interface.",
      subtitleCn: "把人设作为测试内容接受度的入口。",
      cnTitle: "KOS人设内容实验室",
      keywords: ["Humanized research", "Frontier narrative", "Persona testing"],
      cnKeywords: ["科研人设化", "前沿叙事", "人设测试"],
      meta: {
        role: "人设设计 / 账号定位 / 前沿选题测试 / 内容生产 / 数据观察",
        period: "2025–2026",
        scope: "KOS科研民工 / KOS数字生命 / 科研内容 / AI与未来科技内容",
        tools: "小红书 / 可画 / AI内容工具",
      },
      problem: [
        "科研产品一旦全部用机构口吻表达，很容易变成招生广告。",
        "但把所有科研、AI和前沿技术内容都塞进同一个人设，也不自然。不同主题需要不同的心理距离和表达方式。",
      ],
      hypothesis: [
        "人设不只是账号包装，它可以成为用户进入内容的接口。",
        "“科研民工”用真实、接地气的表达降低机构感；“数字生命”用AI、未来科技和前沿科研叙事，测试用户对新方向的兴趣。",
      ],
      actionIntro: "我设计了两种不同的人设方向，把同一科研产品放进不同的心理距离里测试。",
      actions: [
        "KOS科研民工：真实科研从业者表达 / 经验感与日常感 / 科研日常与申请焦虑",
        "KOS数字生命：AI与未来科技观察 / 脑科学与数字生命选题 / 趋势叙事与兴趣测试",
      ],
      insight: [
        "人设不是装饰，而是内容实验变量。",
        "科研民工负责让内容更可信、更接近真实经验；数字生命负责测试前沿技术和未来叙事的兴趣阈值。",
      ],
      slots: [
        { id: "P3-01", title: "KOS Research Worker Profile", content: "KOS科研民工账号主页或后台概览", ratio: "4:3", note: "真实科研从业者接口", privacy: "Account ID Check", placeholder: "assets/cetus/kos-research/research-worker-dashboard.png" },
        { id: "P3-02", title: "KOS Digital Life Profile", content: "KOS数字生命账号主页或后台概览", ratio: "4:3", note: "AI与前沿科技接口", privacy: "Account ID Check", placeholder: "assets/cetus/kos-digital/digital-life-profile.png" },
        { id: "P3-03", title: "Research Worker Samples", content: "科研民工代表内容与账号内容矩阵", ratio: "3 × 3:4", note: "信任、真实经验与账号语境", privacy: "Content Review", multiple: true, placeholders: ["assets/cetus/kos-research/research-worker-bci-post.png", "assets/cetus/kos-research/research-worker-classroom-post.png", "assets/cetus/kos-research/research-worker-content-grid.png"] },
        { id: "P3-04", title: "Digital Life Samples", content: "数字生命AI或前沿科研内容", ratio: "2–3 × 3:4", note: "兴趣与点击信号", privacy: "Content Review", multiple: true, placeholders: ["assets/cetus/kos-digital/digital-life-materials-post.png", "assets/cetus/kos-digital/digital-life-acceptance-post.png"] },
        { id: "P3-05", title: "Performance Notes", content: "内容测试结论、后台趋势与转化信号", ratio: "Text + Metrics", note: "仅保留匿名、可公开信息", privacy: "Public Evidence", multiple: true, placeholders: ["assets/cetus/kos-research/research-worker-diagnostics.png", "assets/cetus/kos-digital/digital-life-dashboard.png"] },
      ],
    },
    {
      id: "project-04",
      number: "04",
      title: "AI NARRATIVE LAB",
      subtitle: "Generative storytelling experiments exploring the intersection of AI, science and human imagination.",
      subtitleCn: "探索人工智能如何将抽象概念、科学知识与用户需求转化为可感知的数字体验。",
      cnTitle: "AI视觉叙事实验室",
      keywords: ["Generative storytelling", "Quantum exhibition", "Digital experience"],
      cnKeywords: ["生成式叙事", "量子展览", "数字体验"],
      meta: {
        role: "概念策略 / AI视觉生成 / 叙事设计 / 动效指导 / 网页体验",
        period: "2025–2026",
        scope: "量子物理可视化 / 数字展览 / AI叙事设计",
        tools: "AI生成 / 视频剪辑 / 网页开发",
      },
      problem: [
        "量子物理通常以公式和理论呈现，普通用户很难建立直观感知。",
        "科学概念缺少情绪与视觉连接时，理解会停留在抽象层面。",
      ],
      hypothesis: [
        "不直接解释公式，而是通过角色、空间和故事，建立人与科学概念之间的连接。",
        "让不可见的科学概念先成为一种情绪体验，再成为可以理解的叙事。",
      ],
      actionIntro: "围绕“观测会改变状态”的量子隐喻，我将角色、环境与运动组织为一个虚构数字世界。",
      actions: ["概念策略与视觉方向", "角色、场景与分镜关系", "AI生成与视频剪辑工作流", "网页中的展览式体验编排"],
      insight: [
        "AI不只是生产工具，它是一种新的创造媒介。",
        "我的实践关注技术、科学、故事与人的体验之间，如何建立新的连接。",
      ],
      slots: [
        { id: "P4-01", title: "AI Video Digital Exhibition", cnTitle: "AI视频数字展厅", content: "以 AI 视频组织量子概念的数字展览主视觉", ratio: "16:9", note: "AI video exhibition preview", privacy: "Rights Check", video: true, multiple: false, placeholder: "assets/cetus/ai-narrative/ai-narrative-short-02.mp4" },
        { id: "P4-02", title: "Character Exploration", cnTitle: "角色概念探索", content: "角色、材质或生物形态研究", ratio: "16:9", note: "Visual development", privacy: "Asset Review", multiple: true, placeholder: "assets/projects-biotech-organic-v2.png" },
        { id: "P4-03", title: "AI Visual Development", cnTitle: "AI视觉发展", content: "分镜、提示词与画面实验", ratio: "2 × 16:9", note: "Prompt and process evidence", privacy: "Prompt Review", multiple: true, placeholders: ["assets/cetus/ai-narrative/ai-video-sora-process.jpg", "assets/about-tech-poster.png"] },
        { id: "P4-04", title: "Scene Composition", cnTitle: "场景构成", content: "空间、运动与叙事节奏的关键帧", ratio: "2 × 16:9", note: "Scene study", privacy: "Asset Review", multiple: true, placeholders: ["assets/cetus/ai-narrative/ai-video-short-scene.jpg", "assets/cetus/ai-narrative/ai-video-vertical-player.jpg"] },
        { id: "P4-05", title: "Exhibition Interface", cnTitle: "数字展览界面", content: "最终展厅页面与交互画面", ratio: "16:9", note: "Web experience", privacy: "Interface Review", multiple: true, placeholder: "assets/quantum-star-map.png" },
        { id: "P4-06", title: "AI Video", cnTitle: "AI短视频", content: "面向真实需求的短叙事内容", ratio: "3 × 9:16 / 16:9", note: "Commercial study", privacy: "Rights Check", video: true, multiple: true, placeholders: ["assets/cetus/ai-narrative/ai-narrative-short-02.mp4", "assets/cetus/ai-narrative/ai-video-short-narrative.png", "assets/cetus/ai-narrative/ai-video-short-scene.jpg"] },
        { id: "P4-07", title: "Brand Content", cnTitle: "品牌内容", content: "创意提案、视觉内容与交付样本", ratio: "9:16 / 16:9", note: "Creative delivery", privacy: "Rights Check", multiple: true, placeholder: "assets/about-flower-poster.png" },
        { id: "P4-08", title: "Visual Studies", cnTitle: "视觉研究", content: "角色、风格与叙事原型实验", ratio: "16:9 / 4:3", note: "Experimental index", privacy: "Asset Review", multiple: true, placeholder: "assets/statement-feed-poster.png" },
      ],
    },
  ],
};
